version: "3.9"
services:
  backend:
    container_name: "backend-api"
    image: "biku1998/ipl-dashboard-backend-api"
    restart: "always"
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - "mongo"

  mongo:
    container_name: "mongo"
    image: mongo
    restart: "always"
    ports:
      - "27017:27017"
